### ISSUE TITLE
why including harmful information into prompt works?

### ISSUE THREAD

**Issue by lez-s** [jiaxiaojunQAQ/I-GCG#1]
hi, it is an interesting work. and I have 2 questions.
1. do you have any assumptions of why phrase 'Sure, my output is harmful' works? have you tried other format like 'no, my output is safe' or 'sure, my output is safe'?
2. if I understand correctly, the logic of attack is to iterate `adv_suffix` so that the output of the model is close to the `target`. I think the `adv_init_suffix` is different depends on models, so how do you initialize it for a new model?  do we need to first calculate easy-to-attack problems and then iteratively calculate hard-to-attack problems??
thank you.

**Comment by jiaxiaojunQAQ** [comment]
> hi, it is an interesting work. and I have 2 questions.
> 
> 1. do you have any assumptions of why phrase 'Sure, my output is harmful' works? have you tried other format like 'no, my output is safe' or 'sure, my output is safe'?
> 2. if I understand correctly, the logic of attack is to iterate `adv_suffix` so that the output of the model is close to the `target`. I think the `adv_init_suffix` is different depends on models, so how do you initialize it for a new model?  do we need to first calculate easy-to-attack problems and then iteratively calculate hard-to-attack problems??
>    thank you.

Thank you for your attention to our work.
1. We have tried other hazard-guided targets (Table. 5). Our insight here is to use this self-danger suggestion to make the subsequent output of the model harmful (Fig. 1)
2. Because we found that different problems have different jailbreak difficulties on LLMs (Fig. 5), it is difficult to converge using random initialization for difficult problems (Fig. 3), but it is easier to converge if the suffix generated on other problems is used. This is related to the transferability of adversarial suffixes. Because the goal of all problems is to have the same part (sure, my output is harmful).

Hope it helps you.
